name: hijriyah_indonesia
description: Convert between Hijri Calendar and Gregorian Calendar date support Arabic and Indonesia.
version: 0.1.5
homepage: https://github.com/taufiqjack/hijriyah_indonesia

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
